import type {
  AnalyticsSnapshot,
  Draft,
  NormalizedAssetCandidate,
  NormalizedTopicCandidate,
  PublishJob,
  SourcePolicy,
  Template,
  Topic,
} from "@/lib/domain";

export const sourcePolicies: SourcePolicy[] = [
  {
    providerKey: "mock_fixture",
    enabled: true,
    ingestionMode: "topic_signal",
    defaultRightsStatus: "approved",
    allowAutoDraft: true,
    allowAutoPublish: false,
    requiresAttributionReview: false,
    blockedCategories: [],
  },
  {
    providerKey: "rss_curated",
    enabled: true,
    ingestionMode: "topic_signal",
    defaultRightsStatus: "review_required",
    allowAutoDraft: true,
    allowAutoPublish: false,
    requiresAttributionReview: true,
    blockedCategories: ["politics", "crime", "opinion"],
  },
  {
    providerKey: "mock_asset_library",
    enabled: true,
    ingestionMode: "asset_source",
    defaultRightsStatus: "approved",
    allowAutoDraft: true,
    allowAutoPublish: false,
    requiresAttributionReview: false,
    blockedCategories: [],
  },
  {
    providerKey: "manual_entry",
    enabled: true,
    ingestionMode: "manual_only",
    defaultRightsStatus: "review_required",
    allowAutoDraft: true,
    allowAutoPublish: false,
    requiresAttributionReview: true,
    blockedCategories: ["politics"],
  },
];

export const normalizedTopicCandidates: NormalizedTopicCandidate[] = [
  {
    providerKey: "mock_fixture",
    sourceType: "mock_json",
    externalRef: "halo-001",
    title: "Massive Ice Halo Appears Over Finland",
    canonicalUrl: "https://example.com/weather-halo",
    domain: "example.com",
    snippet: "Rare atmospheric phenomenon stunned residents early Monday.",
    publishedAt: "2026-03-01T08:00:00.000Z",
    imageUrl: "/mock/halo.svg",
    insetImageUrl: "/mock/halo.svg",
    language: "en",
    rawCategory: "weather",
    tags: ["sky", "cold", "visual"],
    rightsConfidence: "high",
    ingestionNotes: ["Fixture-backed topic for deterministic local ranking."],
  },
  {
    providerKey: "rss_curated",
    sourceType: "rss",
    externalRef: "owl-002",
    title: "Tiny Rescue Owl Learns to Fly Again",
    canonicalUrl: "https://example.com/owl-rehab",
    domain: "example.com",
    snippet: "Wildlife rehab footage is driving strong wholesome engagement.",
    publishedAt: "2026-03-04T12:30:00.000Z",
    imageUrl: "/mock/owl.svg",
    insetImageUrl: "/mock/mask.svg",
    language: "en",
    rawCategory: "animals",
    tags: ["rehab", "cute", "shareable"],
    rightsConfidence: "unknown",
    ingestionNotes: ["Image reuse requires review even when topic passes."],
  },
  {
    providerKey: "manual_entry",
    sourceType: "manual",
    externalRef: "tunnel-003",
    title: "Old Train Tunnel Reopens As a Hidden Hiking Route",
    canonicalUrl: "https://example.com/train-tunnel",
    domain: "example.com",
    snippet: "Travel nostalgia plus scenic footage and local history.",
    publishedAt: "2026-03-06T15:45:00.000Z",
    imageUrl: "/mock/tunnel.svg",
    insetImageUrl: "/mock/tunnel.svg",
    language: "en",
    rawCategory: "travel",
    tags: ["history", "hiking", "oddities"],
    rightsConfidence: "unknown",
    ingestionNotes: ["Manual-entry flow requires final review before publish."],
  },
  {
    providerKey: "mock_fixture",
    sourceType: "mock_json",
    externalRef: "marathon-004",
    title: "Underdog Marathoner Negative Splits the Final 10K",
    canonicalUrl: "https://example.com/marathon-split",
    domain: "example.com",
    snippet: "Running communities are reacting to the pacing strategy and finish footage.",
    publishedAt: "2026-03-07T14:00:00.000Z",
    imageUrl: "/mock/tunnel.svg",
    insetImageUrl: "/mock/halo.svg",
    language: "en",
    rawCategory: "running",
    tags: ["running", "marathon", "training"],
    rightsConfidence: "medium",
    ingestionNotes: ["High overlap with legacy audience interests."],
  },
  {
    providerKey: "rss_curated",
    sourceType: "rss",
    externalRef: "recovery-005",
    title: "Recovery Coach Shares 3 Habits That Cut Post-Run Fatigue",
    canonicalUrl: "https://example.com/recovery-habits",
    domain: "example.com",
    snippet: "Useful training angle with broad crossover into wellness and fitness pages.",
    publishedAt: "2026-03-08T10:00:00.000Z",
    imageUrl: "/mock/owl.svg",
    insetImageUrl: "/mock/mask.svg",
    language: "en",
    rawCategory: "health",
    tags: ["recovery", "fitness", "habits"],
    rightsConfidence: "unknown",
    ingestionNotes: ["Requires careful claim framing before publish."],
  },
  {
    providerKey: "manual_entry",
    sourceType: "manual",
    externalRef: "lift-006",
    title: "Powerlifter’s Slow-Motion Save Is Getting Huge Gym Reactions",
    canonicalUrl: "https://example.com/powerlifter-save",
    domain: "example.com",
    snippet: "High replay value, high gym-share behavior, and easy transformation into original commentary.",
    publishedAt: "2026-03-09T09:30:00.000Z",
    imageUrl: "/mock/halo.svg",
    insetImageUrl: "/mock/mask.svg",
    language: "en",
    rawCategory: "lifting",
    tags: ["lifting", "gym", "strength"],
    rightsConfidence: "medium",
    ingestionNotes: ["Good fit for legacy lifting audience if source clip is transformed."],
  },
  {
    providerKey: "rss_curated",
    sourceType: "rss",
    externalRef: "sports-007",
    title: "Late-Game Relay Exchange Saves the Championship Heat",
    canonicalUrl: "https://example.com/relay-save",
    domain: "example.com",
    snippet: "Fast-twitch sports moment with strong replay and reaction potential.",
    publishedAt: "2026-03-10T18:00:00.000Z",
    imageUrl: "/mock/tunnel.svg",
    insetImageUrl: "/mock/halo.svg",
    language: "en",
    rawCategory: "sports",
    tags: ["sports", "relay", "viral"],
    rightsConfidence: "unknown",
    ingestionNotes: ["Useful broad-reach sports category for queue variety."],
  },
];

export const normalizedAssetCandidates: NormalizedAssetCandidate[] = [
  {
    providerKey: "mock_asset_library",
    assetType: "image",
    localPath: "/data/mock_assets/halo-sky.jpg",
    attributionRequired: false,
    rightsStatus: "approved",
    watermarkRisk: "low",
  },
  {
    providerKey: "mock_asset_library",
    assetType: "image",
    localPath: "/data/mock_assets/owl-forest.jpg",
    attributionRequired: false,
    rightsStatus: "approved",
    watermarkRisk: "low",
  },
];

export const topics: Topic[] = [
  {
    id: "topic-1",
    workspaceId: "workspace-graffiti-run",
    title: "Massive Ice Halo Appears Over Finland",
    summary: "A rare atmospheric halo turned a quiet sunrise into a high-velocity visual topic.",
    category: "weather",
    sourceUrl: "https://example.com/weather-halo",
    sourceDomain: "example.com",
    publishedAt: "2026-03-01T08:00:00.000Z",
    imageUrl: "/mock/halo.svg",
    insetImageUrl: "/mock/halo.svg",
    status: "candidate",
    scores: {
      freshness: 81,
      viral: 92,
      brandFit: 88,
      rightsRisk: 18,
      tragedyRisk: 4,
      politicalRisk: 1,
      duplicateRisk: 22,
      final: 89,
    },
    safetyNotes: ["Non-political weather story.", "Low tragedy and misinformation surface."],
    rightsNotes: ["Use mock asset library or create transformed artwork.", "Do not reuse publisher photography directly."],
  },
  {
    id: "topic-2",
    workspaceId: "workspace-graffiti-run",
    title: "Tiny Rescue Owl Learns to Fly Again",
    summary: "Wholesome wildlife recovery story with strong emotional hook and low brand risk.",
    category: "animals",
    sourceUrl: "https://example.com/owl-rehab",
    sourceDomain: "example.com",
    publishedAt: "2026-03-04T12:30:00.000Z",
    imageUrl: "/mock/owl.svg",
    insetImageUrl: "/mock/mask.svg",
    status: "candidate",
    scores: {
      freshness: 76,
      viral: 90,
      brandFit: 93,
      rightsRisk: 25,
      tragedyRisk: 8,
      politicalRisk: 0,
      duplicateRisk: 17,
      final: 91,
    },
    safetyNotes: ["High wholesome signal.", "Review for medical-claim framing before publish."],
    rightsNotes: ["Approved when rendered with local mock library asset."],
  },
  {
    id: "topic-3",
    workspaceId: "workspace-graffiti-run",
    title: "Old Train Tunnel Reopens As a Hidden Hiking Route",
    summary: "Scenic rediscovery angle pairs well with curiosity-led captions and historical framing.",
    category: "travel",
    sourceUrl: "https://example.com/train-tunnel",
    sourceDomain: "example.com",
    publishedAt: "2026-03-06T15:45:00.000Z",
    imageUrl: "/mock/tunnel.svg",
    insetImageUrl: "/mock/tunnel.svg",
    status: "candidate",
    scores: {
      freshness: 84,
      viral: 78,
      brandFit: 85,
      rightsRisk: 30,
      tragedyRisk: 3,
      politicalRisk: 0,
      duplicateRisk: 12,
      final: 83,
    },
    safetyNotes: ["Travel category remains open.", "Suitable for square or story variants."],
    rightsNotes: ["Manual-source visuals require rights confirmation if not replaced."],
  },
  {
    id: "topic-4",
    workspaceId: "workspace-graffiti-run",
    title: "Underdog Marathoner Negative Splits the Final 10K",
    summary: "Running strategy angle with a satisfying finish and built-in training conversation.",
    category: "running",
    sourceUrl: "https://example.com/marathon-split",
    sourceDomain: "example.com",
    publishedAt: "2026-03-07T14:00:00.000Z",
    imageUrl: "/mock/tunnel.svg",
    insetImageUrl: "/mock/halo.svg",
    status: "candidate",
    scores: {
      freshness: 88,
      viral: 86,
      brandFit: 94,
      rightsRisk: 29,
      tragedyRisk: 2,
      politicalRisk: 0,
      duplicateRisk: 14,
      final: 90,
    },
    safetyNotes: ["Strong overlap with prior running audience.", "Use training framing instead of miracle-performance framing."],
    rightsNotes: ["Prefer transformed stills or licensed race photography."],
  },
  {
    id: "topic-5",
    workspaceId: "workspace-graffiti-run",
    title: "Recovery Coach Shares 3 Habits That Cut Post-Run Fatigue",
    summary: "Health-forward utility topic with strong save potential if phrased as general wellness guidance.",
    category: "health",
    sourceUrl: "https://example.com/recovery-habits",
    sourceDomain: "example.com",
    publishedAt: "2026-03-08T10:00:00.000Z",
    imageUrl: "/mock/owl.svg",
    insetImageUrl: "/mock/mask.svg",
    status: "candidate",
    scores: {
      freshness: 72,
      viral: 74,
      brandFit: 90,
      rightsRisk: 24,
      tragedyRisk: 1,
      politicalRisk: 0,
      duplicateRisk: 18,
      final: 82,
    },
    safetyNotes: ["Avoid medical claims.", "High save/share potential for evergreen wellness content."],
    rightsNotes: ["Use original framing and branded visuals over source screenshots."],
  },
  {
    id: "topic-6",
    workspaceId: "workspace-graffiti-run",
    title: "Powerlifter’s Slow-Motion Save Is Getting Huge Gym Reactions",
    summary: "Strength-sports moment with replay value and easy hook-first captioning for gym audiences.",
    category: "lifting",
    sourceUrl: "https://example.com/powerlifter-save",
    sourceDomain: "example.com",
    publishedAt: "2026-03-09T09:30:00.000Z",
    imageUrl: "/mock/halo.svg",
    insetImageUrl: "/mock/mask.svg",
    status: "candidate",
    scores: {
      freshness: 83,
      viral: 87,
      brandFit: 92,
      rightsRisk: 31,
      tragedyRisk: 1,
      politicalRisk: 0,
      duplicateRisk: 21,
      final: 88,
    },
    safetyNotes: ["Good fit for gym/lifting content lane.", "Keep framing athletic, not dangerous-stunt oriented."],
    rightsNotes: ["Needs transformed still or approved clip-derived frame."],
  },
  {
    id: "topic-7",
    workspaceId: "workspace-graffiti-run",
    title: "Late-Game Relay Exchange Saves the Championship Heat",
    summary: "Broad sports topic with clean stakes, strong replay loop, and team-performance angle.",
    category: "sports",
    sourceUrl: "https://example.com/relay-save",
    sourceDomain: "example.com",
    publishedAt: "2026-03-10T18:00:00.000Z",
    imageUrl: "/mock/tunnel.svg",
    insetImageUrl: "/mock/halo.svg",
    status: "candidate",
    scores: {
      freshness: 91,
      viral: 89,
      brandFit: 86,
      rightsRisk: 28,
      tragedyRisk: 1,
      politicalRisk: 0,
      duplicateRisk: 19,
      final: 92,
    },
    safetyNotes: ["Sports content broadens queue without drifting into politics.", "Good fit for replay-led posts."],
    rightsNotes: ["Use source as signal and recreate composition with branded template."],
  },
];

export const templates: Template[] = [
  {
    id: "template-story",
    workspaceId: "workspace-graffiti-run",
    name: "Story Stack",
    templateType: "story",
    layoutLabel: "Stacked story",
    headlinePlacement: "Lower tilted banner",
    subheadlinePlacement: "Bottom stacked text",
    backgroundStyle: "Dark navy gradient",
    width: 1080,
    height: 1920,
    isDefault: true,
    accentColor: "#ee6c4d",
    headlineLimit: 52,
    notes: "Story-first layout with a tilted headline banner, bottom stack summary, and circular inset for secondary imagery.",
    config: {
      background: {
        overlayOpacity: 0.42,
        overlayStartColor: "11,22,34",
        overlayEndColor: "4,9,13",
      },
      logo: {
        x: 820,
        y: 48,
        width: 200,
      },
      headline: {
        x: 76,
        y: 1450,
        width: 900,
        fontSize: 88,
        rotation: -4,
        paddingX: 28,
        paddingY: 18,
        backgroundColor: "#ffffff",
        color: "#0f1115",
      },
      subheadline: {
        x: 88,
        y: 1600,
        width: 900,
        fontSize: 80,
        color: "#ffffff",
        paddingX: 0,
        paddingY: 0,
      },
      emphasis: {
        color: "#ffd33d",
        keywords: ["first", "again", "wild", "share", "viral", "ston", "mask"],
      },
      insetImage: {
        x: 24,
        y: 70,
        size: 400,
        borderWidth: 8,
        borderColor: "#ffffff",
      },
    },
  },
  {
    id: "template-square",
    workspaceId: "workspace-graffiti-run",
    name: "Lower Third Banner",
    templateType: "square",
    layoutLabel: "Feed standard",
    headlinePlacement: "Lower-third strap",
    subheadlinePlacement: "Footer copy line",
    backgroundStyle: "Charcoal vignette",
    width: 1080,
    height: 1080,
    isDefault: true,
    accentColor: "#214e63",
    headlineLimit: 44,
    notes: "The default feed template: strong lower-third headline, footer summary, and top-corner logo for fast-scanning posts.",
    config: {
      background: {
        overlayOpacity: 0.35,
        overlayStartColor: "15,27,37",
        overlayEndColor: "5,9,13",
      },
      logo: {
        x: 790,
        y: 36,
        width: 220,
      },
      headline: {
        x: 70,
        y: 760,
        width: 930,
        fontSize: 72,
        rotation: -3,
        paddingX: 24,
        paddingY: 18,
        backgroundColor: "#ffffff",
        color: "#0f1115",
      },
      subheadline: {
        x: 82,
        y: 870,
        width: 910,
        fontSize: 64,
        color: "#ffffff",
        paddingX: 0,
        paddingY: 0,
      },
      emphasis: {
        color: "#ffd33d",
        keywords: ["first", "again", "wild", "share", "viral", "stone", "mask"],
      },
      insetImage: {
        x: 24,
        y: 30,
        size: 330,
        borderWidth: 8,
        borderColor: "#ffffff",
      },
    },
  },
  {
    id: "template-carousel",
    workspaceId: "workspace-graffiti-run",
    name: "Split Editorial",
    templateType: "carousel",
    layoutLabel: "Editorial slide",
    headlinePlacement: "Mid-lower slab",
    subheadlinePlacement: "Bottom glass panel",
    backgroundStyle: "Emerald editorial wash",
    width: 1080,
    height: 1080,
    isDefault: false,
    accentColor: "#247a5a",
    headlineLimit: 36,
    notes: "Editorial carousel card with a flatter headline slab and a translucent copy block for context-heavy slides.",
    config: {
      background: {
        overlayOpacity: 0.28,
        overlayStartColor: "16,38,30",
        overlayEndColor: "4,11,9",
      },
      logo: {
        x: 820,
        y: 48,
        width: 190,
      },
      headline: {
        x: 64,
        y: 700,
        width: 940,
        fontSize: 68,
        rotation: 0,
        paddingX: 22,
        paddingY: 18,
        backgroundColor: "#ffffff",
        color: "#0f1115",
      },
      subheadline: {
        x: 72,
        y: 834,
        width: 936,
        fontSize: 48,
        color: "#ffffff",
        paddingX: 26,
        paddingY: 18,
        backgroundColor: "rgba(255,255,255,0.12)",
        radius: 22,
      },
      emphasis: {
        color: "#9ef0c1",
        keywords: ["first", "again", "wild", "share", "viral"],
      },
      insetImage: {
        x: 48,
        y: 60,
        size: 230,
        borderWidth: 6,
        borderColor: "#ffffff",
      },
    },
  },
  {
    id: "template-topline",
    workspaceId: "workspace-graffiti-run",
    name: "Topline Flash",
    templateType: "square",
    layoutLabel: "Breaking-news feed",
    headlinePlacement: "Upper banner",
    subheadlinePlacement: "Middle context panel",
    backgroundStyle: "Burnt-orange warm wash",
    width: 1080,
    height: 1080,
    isDefault: false,
    accentColor: "#d96b31",
    headlineLimit: 40,
    notes: "For fast news hits: a top banner headline, centered context panel, and warm tint that reads like a breaking alert.",
    config: {
      background: {
        overlayOpacity: 0.3,
        overlayStartColor: "58,26,12",
        overlayEndColor: "12,15,20",
      },
      logo: {
        x: 804,
        y: 52,
        width: 206,
      },
      headline: {
        x: 58,
        y: 86,
        width: 770,
        fontSize: 62,
        rotation: 0,
        paddingX: 24,
        paddingY: 18,
        backgroundColor: "#fff4e8",
        color: "#1d1a17",
      },
      subheadline: {
        x: 76,
        y: 690,
        width: 760,
        fontSize: 44,
        color: "#fff4e8",
        paddingX: 24,
        paddingY: 18,
        backgroundColor: "rgba(7,10,14,0.48)",
        radius: 20,
      },
      emphasis: {
        color: "#ffd33d",
        keywords: ["shocking", "first", "again", "wins", "dead", "star"],
      },
      insetImage: {
        x: 820,
        y: 700,
        size: 200,
        borderWidth: 6,
        borderColor: "#fff4e8",
      },
    },
  },
  {
    id: "template-center-card",
    workspaceId: "workspace-graffiti-run",
    name: "Center Spotlight",
    templateType: "square",
    layoutLabel: "Feature spotlight",
    headlinePlacement: "Centered statement card",
    subheadlinePlacement: "Upper kicker panel",
    backgroundStyle: "Cool teal cinematic fade",
    width: 1080,
    height: 1080,
    isDefault: false,
    accentColor: "#2f7f86",
    headlineLimit: 38,
    notes: "A centered statement-card look for profile stories, celebrity reveals, or clearer before/after style posts.",
    config: {
      background: {
        overlayOpacity: 0.34,
        overlayStartColor: "12,40,48",
        overlayEndColor: "4,10,14",
      },
      logo: {
        x: 808,
        y: 54,
        width: 202,
      },
      headline: {
        x: 118,
        y: 582,
        width: 844,
        fontSize: 58,
        rotation: -2,
        paddingX: 28,
        paddingY: 20,
        backgroundColor: "rgba(255,255,255,0.96)",
        color: "#0f1115",
      },
      subheadline: {
        x: 110,
        y: 138,
        width: 560,
        fontSize: 36,
        color: "#f7fafc",
        paddingX: 20,
        paddingY: 16,
        backgroundColor: "rgba(10,16,22,0.46)",
        radius: 18,
      },
      emphasis: {
        color: "#7ef1ff",
        keywords: ["revealed", "finally", "mask", "exclusive", "wins"],
      },
      insetImage: {
        x: 88,
        y: 824,
        size: 170,
        borderWidth: 6,
        borderColor: "#ffffff",
      },
    },
  },
];

export const drafts: Draft[] = [
  {
    id: "draft-1",
    workspaceId: "workspace-graffiti-run",
    topicId: "topic-2",
    templateId: "template-square",
    status: "in_review",
    selectedHeadline: "This Rescue Owl Just Took Its First Flight Back Into the Wild",
    selectedSummary: "A rehab success story with clean emotional payoff and strong share potential.",
    selectedHook: "The owl needed weeks of rehab before attempting a full glide again.",
    renderedAssetPath: "/renders/owl-square-v1.png",
    scheduledFor: "2026-03-12T15:00:00.000Z",
    comments: [
      {
        id: "comment-1",
        author: "Maya",
        body: "Tighten the second caption. Keep the payoff earlier and remove any implied medical advice.",
        createdAt: "2026-03-09T19:20:00.000Z",
      },
      {
        id: "comment-2",
        author: "Avery",
        body: "Visual treatment is solid. Add a source note for the rehab footage reference.",
        createdAt: "2026-03-09T20:15:00.000Z",
      },
    ],
    versions: [
      {
        versionNumber: 1,
        headline: "This Rescue Owl Just Took Its First Flight Back Into the Wild",
        summary: "A rehab success story with clean emotional payoff and strong share potential.",
        hookFact: "The owl needed weeks of rehab before attempting a full glide again.",
        bodyCopy: "Use a warm but factual tone. Focus on the recovery moment rather than dramatizing injury details.",
      },
      {
        versionNumber: 2,
        headline: "After Weeks of Rehab, This Tiny Owl Finally Flew Again",
        summary: "Gentler framing with a more concise emotional arc for feed performance.",
        hookFact: "Early test hops failed before the owl built enough strength to glide.",
        bodyCopy: "Safer caption variant for broad audience distribution and higher sponsor comfort.",
      },
    ],
    captions: [
      {
        id: "caption-1",
        variantName: "Hopeful",
        captionText: "A tiny owl spent weeks rebuilding strength, and this was the moment it finally flew again.",
        ctaText: "Would you stop scrolling for this one?",
        hashtagsText: "#wildlife #owl #wholesome",
      },
      {
        id: "caption-2",
        variantName: "Curiosity",
        captionText: "Most people only see the release. The real story is the slow work that made this flight possible.",
        ctaText: "What part should the next slide explain?",
        hashtagsText: "#animalrescue #nature #storytime",
      },
      {
        id: "caption-3",
        variantName: "Short-form",
        captionText: "Weeks of rehab. One clean glide. Worth the wait.",
        ctaText: "Drop a if you would share this.",
        hashtagsText: "#owl #goodnews #viralstory",
      },
    ],
  },
];

export const publishJobs: PublishJob[] = [
  {
    id: "job-1",
    workspaceId: "workspace-graffiti-run",
    draftId: "draft-1",
    channelName: "Graffiti Run Facebook Page",
    status: "queued",
    scheduledFor: "2026-03-12T15:00:00.000Z",
  },
  {
    id: "job-2",
    workspaceId: "workspace-graffiti-run",
    draftId: "draft-archive-1",
    channelName: "Graffiti Run Facebook Page",
    status: "succeeded",
    scheduledFor: "2026-03-08T14:00:00.000Z",
  },
  {
    id: "job-3",
    workspaceId: "workspace-graffiti-run",
    draftId: "draft-failed-1",
    channelName: "Graffiti Run Facebook Page",
    status: "failed",
    scheduledFor: "2026-03-09T17:30:00.000Z",
    errorMessage: "Missing long-lived page token in local environment.",
  },
];

export const analyticsSnapshot: AnalyticsSnapshot = {
  postsPublished: 32,
  avgReach: 82400,
  avgEngagementRate: 7.4,
  avgShares: 1260,
  estimatedEarnings: 4820,
  recentDelta: "+12.6% vs previous 7 days",
  categoryPerformance: [
    { category: "animals", value: 91 },
    { category: "weather", value: 84 },
    { category: "travel", value: 72 },
    { category: "history", value: 64 },
  ],
  templatePerformance: [
    { template: "Square", value: 88 },
    { template: "Story", value: 74 },
    { template: "Carousel", value: 61 },
  ],
  postingWindows: [
    { label: "7 AM", value: 68 },
    { label: "12 PM", value: 81 },
    { label: "3 PM", value: 93 },
    { label: "7 PM", value: 76 },
  ],
};
