import type {
  AnalyticsSnapshot,
  Draft,
  NormalizedAssetCandidate,
  NormalizedTopicCandidate,
  PublishJob,
  SourcePolicy,
  Template,
  Topic,
} from "@/lib/domain";

export const sourcePolicies: SourcePolicy[] = [
  {
    providerKey: "mock_fixture",
    enabled: true,
    ingestionMode: "topic_signal",
    defaultRightsStatus: "approved",
    allowAutoDraft: true,
    allowAutoPublish: false,
    requiresAttributionReview: false,
    blockedCategories: [],
  },
  {
    providerKey: "rss_curated",
    enabled: true,
    ingestionMode: "topic_signal",
    defaultRightsStatus: "review_required",
    allowAutoDraft: true,
    allowAutoPublish: false,
    requiresAttributionReview: true,
    blockedCategories: ["politics", "crime", "opinion"],
  },
  {
    providerKey: "mock_asset_library",
    enabled: true,
    ingestionMode: "asset_source",
    defaultRightsStatus: "approved",
    allowAutoDraft: true,
    allowAutoPublish: false,
    requiresAttributionReview: false,
    blockedCategories: [],
  },
  {
    providerKey: "manual_entry",
    enabled: true,
    ingestionMode: "manual_only",
    defaultRightsStatus: "review_required",
    allowAutoDraft: true,
    allowAutoPublish: false,
    requiresAttributionReview: true,
    blockedCategories: ["politics"],
  },
];

export const normalizedTopicCandidates: NormalizedTopicCandidate[] = [
  {
    providerKey: "mock_fixture",
    sourceType: "mock_json",
    externalRef: "halo-001",
    title: "Massive Ice Halo Appears Over Finland",
    canonicalUrl: "https://example.com/weather-halo",
    domain: "example.com",
    snippet: "Rare atmospheric phenomenon stunned residents early Monday.",
    publishedAt: "2026-03-01T08:00:00.000Z",
    imageUrl: "/mock/halo.jpg",
    language: "en",
    rawCategory: "weather",
    tags: ["sky", "cold", "visual"],
    rightsConfidence: "high",
    ingestionNotes: ["Fixture-backed topic for deterministic local ranking."],
  },
  {
    providerKey: "rss_curated",
    sourceType: "rss",
    externalRef: "owl-002",
    title: "Tiny Rescue Owl Learns to Fly Again",
    canonicalUrl: "https://example.com/owl-rehab",
    domain: "example.com",
    snippet: "Wildlife rehab footage is driving strong wholesome engagement.",
    publishedAt: "2026-03-04T12:30:00.000Z",
    imageUrl: "/mock/owl.jpg",
    language: "en",
    rawCategory: "animals",
    tags: ["rehab", "cute", "shareable"],
    rightsConfidence: "unknown",
    ingestionNotes: ["Image reuse requires review even when topic passes."],
  },
  {
    providerKey: "manual_entry",
    sourceType: "manual",
    externalRef: "tunnel-003",
    title: "Old Train Tunnel Reopens As a Hidden Hiking Route",
    canonicalUrl: "https://example.com/train-tunnel",
    domain: "example.com",
    snippet: "Travel nostalgia plus scenic footage and local history.",
    publishedAt: "2026-03-06T15:45:00.000Z",
    imageUrl: "/mock/tunnel.jpg",
    language: "en",
    rawCategory: "travel",
    tags: ["history", "hiking", "oddities"],
    rightsConfidence: "unknown",
    ingestionNotes: ["Manual-entry flow requires final review before publish."],
  },
];

export const normalizedAssetCandidates: NormalizedAssetCandidate[] = [
  {
    providerKey: "mock_asset_library",
    assetType: "image",
    localPath: "/data/mock_assets/halo-sky.jpg",
    attributionRequired: false,
    rightsStatus: "approved",
    watermarkRisk: "low",
  },
  {
    providerKey: "mock_asset_library",
    assetType: "image",
    localPath: "/data/mock_assets/owl-forest.jpg",
    attributionRequired: false,
    rightsStatus: "approved",
    watermarkRisk: "low",
  },
];

export const topics: Topic[] = [
  {
    id: "topic-1",
    workspaceId: "workspace-graffiti-run",
    title: "Massive Ice Halo Appears Over Finland",
    summary: "A rare atmospheric halo turned a quiet sunrise into a high-velocity visual topic.",
    category: "weather",
    sourceUrl: "https://example.com/weather-halo",
    sourceDomain: "example.com",
    publishedAt: "2026-03-01T08:00:00.000Z",
    imageUrl: "/mock/halo.jpg",
    status: "candidate",
    scores: {
      freshness: 81,
      viral: 92,
      brandFit: 88,
      rightsRisk: 18,
      tragedyRisk: 4,
      politicalRisk: 1,
      duplicateRisk: 22,
      final: 89,
    },
    safetyNotes: ["Non-political weather story.", "Low tragedy and misinformation surface."],
    rightsNotes: ["Use mock asset library or create transformed artwork.", "Do not reuse publisher photography directly."],
  },
  {
    id: "topic-2",
    workspaceId: "workspace-graffiti-run",
    title: "Tiny Rescue Owl Learns to Fly Again",
    summary: "Wholesome wildlife recovery story with strong emotional hook and low brand risk.",
    category: "animals",
    sourceUrl: "https://example.com/owl-rehab",
    sourceDomain: "example.com",
    publishedAt: "2026-03-04T12:30:00.000Z",
    imageUrl: "/mock/owl.jpg",
    status: "candidate",
    scores: {
      freshness: 76,
      viral: 90,
      brandFit: 93,
      rightsRisk: 25,
      tragedyRisk: 8,
      politicalRisk: 0,
      duplicateRisk: 17,
      final: 91,
    },
    safetyNotes: ["High wholesome signal.", "Review for medical-claim framing before publish."],
    rightsNotes: ["Approved when rendered with local mock library asset."],
  },
  {
    id: "topic-3",
    workspaceId: "workspace-graffiti-run",
    title: "Old Train Tunnel Reopens As a Hidden Hiking Route",
    summary: "Scenic rediscovery angle pairs well with curiosity-led captions and historical framing.",
    category: "travel",
    sourceUrl: "https://example.com/train-tunnel",
    sourceDomain: "example.com",
    publishedAt: "2026-03-06T15:45:00.000Z",
    imageUrl: "/mock/tunnel.jpg",
    status: "candidate",
    scores: {
      freshness: 84,
      viral: 78,
      brandFit: 85,
      rightsRisk: 30,
      tragedyRisk: 3,
      politicalRisk: 0,
      duplicateRisk: 12,
      final: 83,
    },
    safetyNotes: ["Travel category remains open.", "Suitable for square or story variants."],
    rightsNotes: ["Manual-source visuals require rights confirmation if not replaced."],
  },
];

export const templates: Template[] = [
  {
    id: "template-story",
    workspaceId: "workspace-graffiti-run",
    name: "Graffiti Run Story",
    templateType: "story",
    width: 1080,
    height: 1920,
    isDefault: true,
    accentColor: "#ee6c4d",
    headlineLimit: 52,
    notes: "Tall story layout with stacked title, oversized category chip, and bottom CTA.",
  },
  {
    id: "template-square",
    workspaceId: "workspace-graffiti-run",
    name: "Graffiti Run Square",
    templateType: "square",
    width: 1080,
    height: 1080,
    isDefault: true,
    accentColor: "#214e63",
    headlineLimit: 44,
    notes: "Primary feed post layout with left-aligned headline panel and compact footer bar.",
  },
  {
    id: "template-carousel",
    workspaceId: "workspace-graffiti-run",
    name: "Graffiti Run Carousel",
    templateType: "carousel",
    width: 1080,
    height: 1080,
    isDefault: false,
    accentColor: "#247a5a",
    headlineLimit: 36,
    notes: "Slide format optimized for stat or hook-first storytelling.",
  },
];

export const drafts: Draft[] = [
  {
    id: "draft-1",
    workspaceId: "workspace-graffiti-run",
    topicId: "topic-2",
    templateId: "template-square",
    status: "in_review",
    selectedHeadline: "This Rescue Owl Just Took Its First Flight Back Into the Wild",
    selectedSummary: "A rehab success story with clean emotional payoff and strong share potential.",
    selectedHook: "The owl needed weeks of rehab before attempting a full glide again.",
    renderedAssetPath: "/renders/owl-square-v1.png",
    scheduledFor: "2026-03-12T15:00:00.000Z",
    comments: [
      {
        id: "comment-1",
        author: "Maya",
        body: "Tighten the second caption. Keep the payoff earlier and remove any implied medical advice.",
        createdAt: "2026-03-09T19:20:00.000Z",
      },
      {
        id: "comment-2",
        author: "Avery",
        body: "Visual treatment is solid. Add a source note for the rehab footage reference.",
        createdAt: "2026-03-09T20:15:00.000Z",
      },
    ],
    versions: [
      {
        versionNumber: 1,
        headline: "This Rescue Owl Just Took Its First Flight Back Into the Wild",
        summary: "A rehab success story with clean emotional payoff and strong share potential.",
        hookFact: "The owl needed weeks of rehab before attempting a full glide again.",
        bodyCopy: "Use a warm but factual tone. Focus on the recovery moment rather than dramatizing injury details.",
      },
      {
        versionNumber: 2,
        headline: "After Weeks of Rehab, This Tiny Owl Finally Flew Again",
        summary: "Gentler framing with a more concise emotional arc for feed performance.",
        hookFact: "Early test hops failed before the owl built enough strength to glide.",
        bodyCopy: "Safer caption variant for broad audience distribution and higher sponsor comfort.",
      },
    ],
    captions: [
      {
        id: "caption-1",
        variantName: "Hopeful",
        captionText: "A tiny owl spent weeks rebuilding strength, and this was the moment it finally flew again.",
        ctaText: "Would you stop scrolling for this one?",
        hashtagsText: "#wildlife #owl #wholesome",
      },
      {
        id: "caption-2",
        variantName: "Curiosity",
        captionText: "Most people only see the release. The real story is the slow work that made this flight possible.",
        ctaText: "What part should the next slide explain?",
        hashtagsText: "#animalrescue #nature #storytime",
      },
      {
        id: "caption-3",
        variantName: "Short-form",
        captionText: "Weeks of rehab. One clean glide. Worth the wait.",
        ctaText: "Drop a if you would share this.",
        hashtagsText: "#owl #goodnews #viralstory",
      },
    ],
  },
];

export const publishJobs: PublishJob[] = [
  {
    id: "job-1",
    workspaceId: "workspace-graffiti-run",
    draftId: "draft-1",
    channelName: "Graffiti Run Facebook Page",
    status: "queued",
    scheduledFor: "2026-03-12T15:00:00.000Z",
  },
  {
    id: "job-2",
    workspaceId: "workspace-graffiti-run",
    draftId: "draft-archive-1",
    channelName: "Graffiti Run Facebook Page",
    status: "succeeded",
    scheduledFor: "2026-03-08T14:00:00.000Z",
  },
  {
    id: "job-3",
    workspaceId: "workspace-graffiti-run",
    draftId: "draft-failed-1",
    channelName: "Graffiti Run Facebook Page",
    status: "failed",
    scheduledFor: "2026-03-09T17:30:00.000Z",
    errorMessage: "Missing long-lived page token in local environment.",
  },
];

export const analyticsSnapshot: AnalyticsSnapshot = {
  postsPublished: 32,
  avgReach: 82400,
  avgEngagementRate: 7.4,
  avgShares: 1260,
  estimatedEarnings: 4820,
  recentDelta: "+12.6% vs previous 7 days",
  categoryPerformance: [
    { category: "animals", value: 91 },
    { category: "weather", value: 84 },
    { category: "travel", value: 72 },
    { category: "history", value: 64 },
  ],
  templatePerformance: [
    { template: "Square", value: 88 },
    { template: "Story", value: 74 },
    { template: "Carousel", value: 61 },
  ],
  postingWindows: [
    { label: "7 AM", value: 68 },
    { label: "12 PM", value: 81 },
    { label: "3 PM", value: 93 },
    { label: "7 PM", value: 76 },
  ],
};
